version: '3'
services:
  webserver:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /var/www/sder_blog:/var/www/sder_blog
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
  
  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - /var/www/sder_blog:/var/www/sder_blog
