import './bootstrap';
import './action-buttons';
// import './ascenso';
// import './crud-persons';
// import './equipo-tecnico';
// import './form';
import './lightbox';
import './main';
// import './navs';
// import './questions';
// import './slider';
// import './tabs';